changes to SQL code to make it work for TSQL
dbt-labs/jaffle-shop-classic pull request #6
Opened 2021-07-08 17:48 UTC by chaerinlee1

Small syntax changes in the `customers.sql` and `orders.sql` file to make it work for TSQL users.

2021-07-08 17:51 UTC, swanderz commented on dbt_project.yml
> +      +as_columnstore: False
@chaerinlee1 this isn't relevant for non dbt-sqlserver users
```suggestion
```

2021-07-08 17:58 UTC, swanderz approved these changes
@chaerinlee1 this looks good to me! all of these syntax tweaks should run cross platform

2021-09-09 17:28 UTC, swanderz requested changes
@chaerinlee1 I'd like to propose as few changes as possible, so removed your table aliasing (e.g. `o.` and `op.`)

2021-09-09 17:28 UTC, swanderz commented on models/orders.sql
> +        o.status,
```suggestion
        orders.order_id,
        orders.customer_id,
        orders.order_date,
        orders.status,
```

2021-09-09 17:28 UTC, swanderz commented on models/orders.sql
> +        op.{{ payment_method }}_amount,
```suggestion
        order_payments.{{ payment_method }}_amount,
```

2021-09-09 17:28 UTC, swanderz commented on models/orders.sql
> +        op.total_amount as amount
```suggestion
        order_payments.total_amount as amount
```

2021-09-09 17:28 UTC, swanderz commented on models/orders.sql
> +    from orders o
```suggestion
    from orders
```

2021-09-09 17:28 UTC, swanderz commented on models/orders.sql
> +    left join order_payments op on o.order_id=op.order_id
```suggestion
    left join order_payments on orders.order_id = order_payments.order_id
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +        cp.total_amount as customer_lifetime_value
```suggestion
        customers.customer_id,
        customers.first_name,
        customers.last_name,
        customer_orders.first_order,
        customer_orders.most_recent_order,
        customer_orders.number_of_orders,
        customer_payments.total_amount as customer_lifetime_value
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    from customers c
```suggestion
    from customers
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    left join customer_payments cp on cp.customer_id=c.customer_id
```suggestion
    left join customer_payments
        on  customers.customer_id = customer_payments.customer_id
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    left join customer_orders co on c.customer_id=co.customer_id
```suggestion
    left join customer_orders
        on customers.customer_id = customer_orders.customer_id
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    left join orders o on o.order_id=p.order_id
```suggestion
    left join orders on
         payments.order_id = orders.order_id
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    from payments p
```suggestion
    from payments
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +        o.customer_id,
```suggestion
        orders.customer_id,
```

2021-09-09 17:28 UTC, swanderz commented on models/customers.sql
> +    group by o.customer_id
```suggestion
    group by orders.customer_id
```

2021-09-09 18:05 UTC, swanderz approved these changes
thanks @chaerinlee1

2021-09-09 18:47 UTC, annafil commented on models/orders.sql
> +    left join order_payments on orders.order_id = order_payments.order_id
```suggestion
    left join order_payments 
        on orders.order_id = order_payments.order_id
```

2021-09-09 18:49 UTC, annafil approved these changes
Thank you both for these changes! Agree with Anders re: removing table aliases, this is consistent with the [style guide](https://github.com/dbt-labs/corp/blob/master/dbt_style_guide.md) we use in our projects.

2021-09-09 18:50 UTC, merged